fix: update yaml indentation again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -117,11 +117,11 @@ jobs:
           cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
       - name: Coverage single fail - exit
         if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-          run: |
-            echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-            exit 1
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+          exit 1
       - name: Coverage total fail - exit
         if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-          run: |
-            echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-            exit 1
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+          exit 1
